[package]
name = "colourblind-helper"
version = "0.1.0"
authors = ["Hannah McLaughlin <h@mcla.ug>"]

[dependencies]
image = "*"
imageproc = "*"
itertools = "0.5.4"

[dev-dependencies]
quickcheck = "0.3"
rand = "0.3"

